name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: https://github.com/actions/checkout@v4

      - name: Get version
        id: version
        uses: https://github.com/home-assistant/actions/helpers/version@master

      - name: "Set manifest version number"
        run: |
          python3 ${{ github.workspace }}/.github/scripts/update_hacs_manifest.py --version ${{ steps.version.outputs.version }}

      - name: Create zip
        run: |
          cd custom_components/myorlen_gas_sensor
          zip myorlen_gas_sensor.zip -r ./
      - name: Upload zip to release
        uses: https://github.com/svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./custom_components/myorlen_gas_sensor/myorlen_gas_sensor.zip
          asset_name: myorlen_gas_sensor.zip
          tag: ${{ github.ref }}
          overwrite: true